<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<LangVersion>9</LangVersion>
		<AssemblyName>myll_lib</AssemblyName>
		<RootNamespace>Myll</RootNamespace>
		<Authors>Jan "SoRDiD" Reitz</Authors>
		<Description>Backend of the Myll Programming Language</Description>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<Antlr4UseStandardTool>true</Antlr4UseStandardTool>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<NoWarn>1701;1702;3021</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
	  <NoWarn>1701;1702;3021</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1"/>
		<PackageReference Include="Antlr4BuildTasks" Version="12.14.0" PrivateAssets="all"/>
	</ItemGroup>

	<ItemGroup>
		<Antlr4 Include="Grammar/MyllLexer.g4">
			<Listener>false</Listener>
			<Visitor>false</Visitor>
			<Package>Myll</Package>
			<TargetLanguage>CSharp</TargetLanguage>
		</Antlr4>
		<Antlr4 Include="Grammar/MyllParser.g4">
			<Listener>false</Listener>
			<Visitor>true</Visitor>
			<Package>Myll</Package>
			<TargetLanguage>CSharp</TargetLanguage>
		</Antlr4>
	</ItemGroup>

	<ItemGroup>
	  <None Remove="backend.csproj.DotSettings" />
	</ItemGroup>

</Project>
