Language: CSharp
BasedOnStyle: Microsoft
UseTab: ForContinuationAndIndentation
TabWidth: 4
IndentWidth: 4
ContinuationIndentWidth: 4
ColumnLimit: 200
BreakBeforeBraces: Custom
BraceWrapping:
  AfterNamespace: true
  AfterClass: true
  AfterEnum: true
  AfterFunction: true
  AfterControlStatement: false
  BeforeElse: true
  BeforeLambdaBody: true
  BeforeWhile: false
  SplitEmptyFunction: false
AllowShortFunctionsOnASingleLine: All
AllowShortIfStatementsOnASingleLine: Never
AllowShortBlocksOnASingleLine: Empty
AllowShortLambdasOnASingleLine: Empty
SpaceBeforeParens: Never
SpacesInParentheses: true
SpaceInEmptyParentheses: false
SpacesInConditionalStatement: true
SpacesInLineCommentPrefix:
  Minimum: 0
  Maximum: -1
SpaceBeforeSquareBrackets: false
SpaceBeforeAssignmentOperators: true
SpaceInEmptyBlock: false
AlignConsecutiveAssignments:
  Enabled: true
  AcrossEmptyLines: false
  AcrossComments: true
AlignConsecutiveDeclarations:
  Enabled: true
  AcrossEmptyLines: false
  AcrossComments: true
  AlignFunctionDeclarations: false
AlignAfterOpenBracket: false
BreakFunctionDefinitionParameters: true
BinPackParameters: AlwaysOnePerLine
BinPackArguments: false
AllowAllParametersOfDeclarationOnNextLine: true
AllowAllArgumentsOnNextLine: true
AlignTrailingComments:
  Kind: Always
MaxEmptyLinesToKeep: 1
KeepEmptyLinesAtTheStartOfBlocks: false
NamespaceIndentation: All
IndentCaseLabels: true
IndentPPDirectives: BeforeHash
SortUsingDeclarations: false
